platform :ios, '10.0'

target 'DemoLightbox' do
  use_frameworks!
	pod 'Lightbox', path: '../../'
  pod 'Cache', git: 'https://github.com/systembugtj/Cache.git'
  pod 'Imaginary', git: 'https://github.com/systembugtj/Imaginary.git'
end
